export enum Events {
    _3x3 = "3x3",
    _2x2 = "2x2",
    _4x4 = "4x4",
    _5x5 = "5x5",
    _6x6 = "6x6",
    _7x7 = "7x7",
    SQUARE_1 = "Square-1",
    PYRAMINX = "Pyraminx",
    SKEWB = "Skewb",
    CLOCK = "Clock",
    MEGAMINX = "Megaminx",
    _3_BLIND = "3 Blind",
    _4_BLIND = "4 Blind",
    _5_BLIND = "5 Blind",
    FMC = "FMC",
    OH = "OH",
    MULTI_BLIND = "Multi Blind",
}